### ISSUE TITLE
release file from repo

### ISSUE THREAD

**Issue by IGImonster** [Dexogen/pipbs#1]
Hi I would like to use your repo, here I noticed two things.
The release file was not renewed at the last altuallisieren therefore the files are no longer correct and apt complains.

My debain only accepted your repo when I changed the link as follows.

deb https://dexogen.github.io/pipbs/main ./

**Comment by dexogen** [comment]
Thank you for noticing this. I'll build a fresh packages and make corrections soon.

**Comment by dexogen** [comment]
I built the new 2.3-1 packages and rebuilt release file. Redownload the gpg key and the process should be fine.
I also corrected the line with the repository address to the correct one as you indicated.

*https://raw.githubusercontent.com/Dexogen/pipbs/main/main/pipbs.list*
```bash
deb [signed-by=/etc/apt/keyrings/pipbs.gpg] https://dexogen.github.io/pipbs/main ./
```

**Comment by IGImonster** [comment]
Nice it works.
Thanks for your work.
