### ISSUE TITLE
Installation fails: you have requested an impossible situation

### ISSUE THREAD

**Issue by BorisBrock** [Dexogen/pipbs#2]
On a fresh RaspberryPi with PiOS 64 bite lite, the installtion fails with the following error:

`sudo apt-get install proxmox-backup-server`

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 proxmox-backup-server : Depends: libsgutils2-2 (>= 1.43) but it is not installable
                         Recommends: ifupdown2 but it is not going to be installed
                         Recommends: proxmox-offline-mirror-helper but it is not installable
                         Recommends: proxmox-mail-forward but it is not installable
E: Unable to correct problems, you have held broken packages.

```

**Comment by dexogen** [comment]
Hi! Thanks for your interest in my repository. I have almost completed the automatic deployment. I hope to find time to finish it within a week.

**Comment by BorisBrock** [comment]
That would be really awesome! Can't wait to try it out.
Thank you for your effort :+1:

**Comment by BorisBrock** [comment]
@Dexogen Hi, did you make any progress on the deployment script? Can't wait to try it :-)

**Comment by dexogen** [comment]
> @Dexogen Hi, did you make any progress on the deployment script? Can't wait to try it :-)

I just added automatic repository updates. Plese [try the new version 3.2.2](https://github.com/Dexogen/pipbs/blob/main/README.md) according to the instructions. Everything should work.

**Comment by BorisBrock** [comment]
@Dexogen Just tried it. But this step:
`curl -fsSL https://dexogen.github.io/pipbs/gpg.key | gpg --dearmor -o /etc/apt/keyrings/pipbs.gpg`
gives me a 404 error:

> curl: (22) The requested URL returned error: 404

**Comment by dexogen** [comment]
@BorisBrock  Try it now please. The file is now [downloading successfully](https://dexogen.github.io/pipbs/gpg.key).

**Comment by BorisBrock** [comment]
@Dexogen I just gave it another try. Still no luck tho:

`sudo curl -fsSL https://dexogen.github.io/pipbs/gpg.key | gpg --dearmor -o /etc/apt/keyrings/pipbs.gpg`

Yields:

> File '/etc/apt/keyrings/pipbs.gpg' exists. Overwrite? (y/N) y
> gpg: can't create '/etc/apt/keyrings/pipbs.gpg': Permission denied
> gpg: no valid OpenPGP data found.
> gpg: dearmoring failed: Permission denied

PS: Solved it by adding a second "sudo":

`sudo curl -fsSL https://dexogen.github.io/pipbs/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/pipbs.gpg`

But now the next command is giving me an error:

`sudo echo "deb [arch=arm64 signed-by=/etc/apt/keyrings/pipbs.gpg] https://dexogen.github.io/pipbs/ bookworm main" > /etc/apt/sources.list.d/pipbs.list`

> -bash: /etc/apt/sources.list.d/pipbs.list: Permission denied

**Comment by BorisBrock** [comment]
@Dexogen I finally figured it out :-)

- I used "sudo" where neccessary
- The "legacy method" does not work (the recommended one does)
- I had to edit pipbs.list manually with nano

I have created a PR to adjust the README.md accordingly (except for point 3). Merge it if you like ;-)
