### ISSUE TITLE
Initial login to PBS not working

### ISSUE THREAD

**Issue by BorisBrock** [Dexogen/pipbs#4]
I installed the Proxmox Backup Server according to your description. After the installation I open the web interface via

http://myraspi:8007

But now I'm unable to log in. According to the official PBS documentation, the initial user name is "root" and the password is whatever has been set during the installation. But here's the problem: during the installation no password was requested at all.
Also using my raspberry pi user's password does not work.

**Suggestions:**

- Add another section to the Readme describing the initial login
- Where can I find the web interface? (http://myraspi:8007)
- Which user name and password have to be used?

**Comment by dexogen** [comment]
**Username:** root
**Password:** your system root-user
**Realm:** Linux PAM standard authentication

Please make sure that the system root-user has a password.

You can also try creating a user in the native pbs realm, as described in the [documentation](https://pbs.proxmox.com/docs/user-management.html).

**Comment by BorisBrock** [comment]
On the default Raspberry Pi image the root user has no password. Thus the login does not work.
It can be fixed like this:

1. Run `sudo passwd` via SSH
2. Enter a password for the root user (and confirm it)
3. Reboot the pi with `sudo reboot now`
4. Call http://myraspi:8007/ and log in with "root" and your new password

Maybe it would make sense to add this to the end of the Readme.md?

**Comment by dexogen** [comment]
> Maybe it would make sense to add this to the end of the Readme.md?

This depends on the OS distribution you are using. For example, Armbian already has a password set for root. But you're right, I'll add a note.
