### ISSUE TITLE
Missing public key error

### ISSUE THREAD

**Issue by logicito** [Dexogen/pipbs#7]
Hi, thank you for putting this together, it's great. 

I installed PBS on RPi 4B following the repo instructions, everything went well, the only problem is when I try to perform an update (apt update) I get the following error:

<img width="1496" alt="image" src="https://github.com/user-attachments/assets/44919e0e-3031-48a1-9c85-447293d173cb">

Please any guidance on how to fix it will be appreciated, thank you

**Comment by dexogen** [comment]
Hey! Looks like the official Proxmox repos got added when installing packages. You can either [add the key](https://pbs.proxmox.com/docs/installation.html#secureapt) or just remove those repos.

**Comment by logicito** [comment]
> Hey! Looks like the official Proxmox repos got added when installing packages. You can either [add the key](https://pbs.proxmox.com/docs/installation.html#secureapt) or just remove those repos.

Got it, thank you

**Comment by logicito** [comment]
Thanks
