### ISSUE TITLE
Question (not an issue)

### ISSUE THREAD

**Issue by logicito** [Dexogen/pipbs#8]
Future releases from the wofferl repository will be reflected here, and on the next apt update that I will execute, those will be updated on my device as well? Thank you

**Comment by dexogen** [comment]
Yep, the GitHub Action [grabs](https://github.com/Dexogen/pipbs/blob/6c05924a298d87fc1619637f58c1be8a09a67117/.github/workflows/main.yml#L29) deb packages from the latest available release at [wofferl repository](https://github.com/wofferl/proxmox-backup-arm64/releases) once a week.
