### ISSUE TITLE
web gui login

### ISSUE THREAD

**Issue by roachovans** [Dexogen/pipbs#9]
Dear,

I have pipbs installed on my pi 5 When I surf to the browser to the IP of the RPI with port 8007, I am asked for a username and a password, where can I find these?

thanks in advance.

regards,
roachovans

**Comment by dexogen** [comment]
Hello, it's just your system root password.

Username: root
Password: the password of your systems root-user
Realm: Linux PAM standard authentication

Or you can create user via cli:

`proxmox-backup-manager user update root@pam --password {pwd}`

more info: https://pbs.proxmox.com/docs/user-management.html

**Comment by roachovans** [comment]
@Dexogen , thank for the solution.

Regards 
roachovans
